// Ataya Harmony UI Kit — Shared Design Tokens
// Used by all UI kit components

Object.assign(window, {
  COLORS: {
    brandBlue: '#125695',
    sidebarBlue: '#126E95',
    linkBlue: '#1A8AFA',
    cyan: '#01BCF3',
    teal: '#46D5B3',
    tealDark: '#469367',
    cyanLight: '#C0E5F4',
    warning: '#FFB800',
    error: '#FF4930',
    errorMid: '#E8633D',
    info: '#48A6F6',
    textPrimary: '#141414',
    textSecondary: '#394463',
    textMuted: '#6A6F81',
    textDisabled: '#C4C4C4',
    textOnDark: '#FFFFFF',
    surfacePage: '#F4F7F9',
    surfaceCard: '#FFFFFF',
    surfaceSelected: '#E5E5E5',
    border: '#D9E3F0',
    borderLight: '#E2EAF4',
    gray100: '#EEF0F1',
    gray300: '#D3D3D3',
    headerBg: '#000000',
    sidebarBg: '#126E95',
    buttonHover: '#FFB82C',
  },
  FONTS: {
    sans: '"Work Sans", "Roboto", sans-serif',
    ui: '"Roboto", "Work Sans", sans-serif',
    mono: '"Menlo", "Consolas", monospace',
  },
  SHADOWS: {
    card: '0px 0px 22px 0.05px #EFEFEF',
    cardHover: '0px 5px 25px rgba(1,188,243,0.2)',
    headerGlow: '0px 0px 28px 0.4px rgba(26,138,250,0.4)',
    button: '0px 4px 4px rgba(26,138,250,0.1)',
  },
  RADIUS: {
    sm: '4px', md: '6px', lg: '10px', full: '16px', circle: '50%',
  },
  NAV_ITEMS: [
    { key: 'analytics', label: 'Insight & Analytics', icon: 'analytic' },
    { key: 'networks',  label: 'Networks',             icon: 'network', active: true },
    { key: 'clients',   label: 'Clients & Policies',   icon: 'client' },
    { key: 'edge',      label: 'Edge Application',     icon: 'devices' },
    { key: 'org',       label: 'Organization',         icon: 'tenant' },
  ],
  SIDE_ITEMS: [
    { key: 'overview',   label: 'Network Overview', icon: 'overview',   active: true },
    { key: 'ran',        label: 'RAN Management',   icon: 'radio' },
    { key: 'clients',    label: 'Clients',          icon: 'client' },
    { key: 'policies',   label: 'Policies',         icon: 'policy' },
    { key: 'sim',        label: 'SIM Inventory',    icon: 'sim' },
    { divider: true },
    { key: 'analytics',  label: 'Analytics',        icon: 'analytic' },
    { key: 'settings',   label: 'Settings',         icon: 'setting' },
  ],
});
